### ISSUE TITLE
Please provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [matthinc/HomeAssistantElectron#10]
Please provide the AppImage for download, too. Thanks.

**Comment by matthinc** [comment]
Yes, that should be possible. I just built an AppImage-file from the project. I will test tomorrow on a VM if it works and include it in the next build.

**Comment by probonopd** [comment]
How did it go @matthinc?

**Comment by matthinc** [comment]
Sorry, that it took so much time....

I had some problems with my Computer and then I had to learn for some exams. I'll try to upload that file today.

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by matthinc** [comment]
Ok - I added the .AppImage to the latest release :
https://github.com/matthinc/HomeAssistantElectron/releases/tag/v0.5.0

Does it work on your machine?

**Comment by probonopd** [comment]
Thank you, works for me on openSUSE LEAP 42.2.
