### ISSUE TITLE
History Graphs in Cards Truncated.

### ISSUE THREAD

**Issue by rudders** [matthinc/HomeAssistantElectron#15]
I have noticed that history_graphs in cards are truncated rather than resized to fit the available card width. MacOS High Sierra 10.13.3. Hass .62.1 on Hassio. V1.1 of your (AWESOME!!!!!) app.

Here is a screenshot of the same card in the app and in Chrome 65 - same result in Safari. 

currently have the following in configuration.yaml

```
frontend:
  javascript_version: es5
```

![1b55c6d8-e8b6-4d5c-b4a2-99b388de0d38](https://user-images.githubusercontent.com/104969/35830030-f1682c44-0b18-11e8-930b-11c636de20b8.png)

**Comment by rudders** [comment]
actually this seems to be inconsistent - I'll try and reproduce reliably and resubmit,

**Comment by rudders** [comment]
Restarting the app does seem to resolve the issue temporarily.

**Comment by matthinc** [comment]
i'm pretty jealous of your air temperature ;D

I don't have a history_graph in my config, but I this seems like a good opportunity to add one. I hope I'm able to reproduce and fix it.

**Comment by rudders** [comment]
Well if you don’t I’ll demand my money back, oh wait...... love your work..... let me know if I can assist in any way.

I also noted there’s no way to quit the app on MacOS in Cmd-q doesn’t work and no menu item.

**Comment by rudders** [comment]
Problem is now gone away ...
