### ISSUE TITLE
New release please...

### ISSUE THREAD

**Issue by rudders** [matthinc/HomeAssistantElectron#16]
Any chance you could package up your menu and other fixes from 1.1? The Menu fix would be handy on MacOS - I tried to hack the js but caused other problems. Thanks.

**Comment by matthinc** [comment]
Oh yes... here it is: https://github.com/matthinc/HomeAssistantElectron/releases/tag/v1.1.1

I really wanted to do this earlier, but my exams got somehow in the way...

**Comment by rudders** [comment]
Thanks mate. Might have a go at forking it and having a play around. But thanks for the release. CMD-q is kind of handy ;)
