### ISSUE TITLE
Configurator iFrame not working

### ISSUE THREAD

**Issue by sareenp2** [matthinc/HomeAssistantElectron#19]
I recently started using your this app to manage my home assistant and it is truly awesome! I am however having an issue with the configurator addon. I added it to my home assistant frontend using iframe and it is also using SSL along with a username and password. I'm not sure if you can fix it but if you could that would be awesome! Also if you could get html5 notifications working with electron (if that is even possible) that would even cooler!

**Comment by matthinc** [comment]
Hi,
thank you for the feedback. Could you please explain the issue a bit further?
Does it just not show, do you receive an error etc.

**Comment by sareenp2** [comment]
It simply says 'no auth header'. I've attached a picture below
![untitled](https://user-images.githubusercontent.com/34289212/40202583-6f0e8708-59f0-11e8-9907-106d3ee4967c.jpeg)

**Comment by rudders** [comment]
The configurator app has its own userid and password. It also times out after a while and there is no way I’ve found for the Elektron based app to get it to ask for the credentials again, it simply returns the auto error. I have this in a hass.io based install.

**Comment by rudders** [comment]
![Image](https://i.imgur.com/Sda9MyU.jpg)

Happens in iOS app also so it’s not this app I don’t believe - it’s the behaviour of the Configurator app.

**Comment by matthinc** [comment]
An easy fix would be this (it's already working for me), but the harder part is to show the dialog. Electron doesn't have a library for that :/

app.on('login', function(event, webContents, request, authInfo, callback) {
  event.preventDefault()
  callback('username','password')
})

**Comment by sareenp2** [comment]
Where/how would I be able to implement this?

**Comment by matthinc** [comment]
<img width="426" alt="screen shot 2018-05-17 at 23 41 45" src="https://user-images.githubusercontent.com/6898797/40205332-f04ca83c-5a2b-11e8-971c-40ad3f2a6e41.png">

You don't have to - I will add it to the settings. Will be done tomorrow

**Comment by sareenp2** [comment]
Awesome, thanks for the quick update!

**Comment by rudders** [comment]
Sweet! Kudos!

**Comment by matthinc** [comment]
@sareenp2 Could you please test this version (It works for me, but I don't have SSL): https://github.com/matthinc/HomeAssistantElectron/releases/tag/conf_test

You can enter the credentials in the preferences.

**Comment by sareenp2** [comment]
Yup, it seems to work fine for me!
