### ISSUE TITLE
OS X - Drop down lists sorted in a non deterministic order

### ISSUE THREAD

**Issue by Kane610** [matthinc/HomeAssistantElectron#20]
The dropdown lists of entities on Mac OS X is sorted in a non deterministic order. It would be much better to have it devices sorted in alphabetical order.

BR Robban

**Comment by KmanOz** [comment]
+1 on OSX

**Comment by matthinc** [comment]
https://github.com/matthinc/HomeAssistantElectron/commit/6f7c8c959e61cee5f8c9bd6da5427e37d02d05ee

**Comment by KmanOz** [comment]
Cheers thank you.
