### ISSUE TITLE
No an issue but probably a stupid question

### ISSUE THREAD

**Issue by KmanOz** [matthinc/HomeAssistantElectron#21]
I notice in your README you have HA shown with different colours to the standard HA. How is that done?

Been stuck on HA 49.1 for a long time as I don't get a chance to keep upgrading. Only upgraded to 69.1 today. Is that a new feature on HA or in your Electron app ?

Great BTW

**Comment by rudders** [comment]
https://github.com/maartenpaauw/home-assistant-community-themes

**Comment by KmanOz** [comment]
Wow thanks. Thought it was a silly question so deleted it. My my HA has come a long way since my last update. Been on 49.1 for a long time. Thanks again.
