### ISSUE TITLE
App doesn't remember screen position

### ISSUE THREAD

**Issue by Phontana** [matthinc/HomeAssistantElectron#8]
When I open the app, it always opens at the center of the screen instead of the last position where I put it.

**Comment by matthinc** [comment]
Thank you for the suggestion. That's a good idea and easy to implement. Will be in the next update.

**Comment by Phontana** [comment]
I just tested the new release and it doesn't remember screen position in this version (0.5.0).

**Comment by matthinc** [comment]
Fixed in 05d5572b7b4b822fb8fdea1584f7aac782d01431
