### ISSUE TITLE
Cmd + H & cmd + W don't work

### ISSUE THREAD

**Issue by Phontana** [matthinc/HomeAssistantElectron#9]
Cmd + H (hide window) & cmd + W (close window) don't work in this app, unlike other Mac apps.

**Comment by Phontana** [comment]
Maybe this helps: https://github.com/electron/electron/issues/5536

**Comment by matthinc** [comment]
I will add shortcuts soon. But does ⌘W make much sense?
The app has only one window and can be closed with ⌘Q.

**Comment by Phontana** [comment]
Yes, it makes sense because almost all macOS apps close the window (but not the app) with ⌘W. Also, in the new 0.5.0 release, the ⌘H shortcut doesn't work the same like other apps.

**Comment by matthinc** [comment]
The shortcuts are now CMD+1, CMD+2...
